// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6m7zlKopcJQkHMi_mN5HWkzJok-TqTcY',
    appId: '1:299731885134:web:2e362d43f85509d1c5b71f',
    messagingSenderId: '299731885134',
    projectId: 'housely-f074b',
    authDomain: 'housely-f074b.firebaseapp.com',
    storageBucket: 'housely-f074b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvxMb_wHehNPY0Xj0ymBMTsYcB6Mhex7k',
    appId: '1:299731885134:android:b267f1fdaa544594c5b71f',
    messagingSenderId: '299731885134',
    projectId: 'housely-f074b',
    storageBucket: 'housely-f074b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Zyb_NZLFWARNlDE2oh-SGBQwnAe-WfA',
    appId: '1:299731885134:ios:9dd23fb9e5a039b1c5b71f',
    messagingSenderId: '299731885134',
    projectId: 'housely-f074b',
    storageBucket: 'housely-f074b.firebasestorage.app',
    iosClientId: '299731885134-v3986q5kpjdmidb3re36odgu509qrred.apps.googleusercontent.com',
    iosBundleId: 'com.example.housely',
  );
}
